### ISSUE TITLE
Turn Fluture into a peerDependency

### ISSUE THREAD

**Issue by Avaq** [sotojuan/fugot#18]
Using Fugot is a bit painful, because if I want to combine its returned Futures with my own (Fluture) Futures, I have to have a compatible version of Fluture installed. Whenever a new incompatible Fluture version is released, I cannot update my Fluture dependency until fugot gets an update.

As suggested in the [latest Fluture release notes](https://github.com/fluture-js/Fluture/releases/tag/6.3.0) all of these problems will go away when Fluture is specified under `peerDependencies`, rather than `dependencies`.

By the looks of it, you're only using two features from Fluture: Its constructor, and its `reject` function. This means that your library could be compatible with a very large range of Future versions. *All versions* if I'm not mistaken. You don't know what will break in the next major version, so I would specify the dependency as follows:

```json
{
  "peerDependencies": {
    "fluture": "<7.0.0"
  }
}
```

Then when a new major version of Fluture is released, you could check if it works and bump the constraint to `8.0.0` in a patch release of Fugot.

---

This is an idea I'm only toying with recently. Any feedback is appreciated.

**Comment by sotojuan** [comment]
I'll give this a try - makes perfect sense!

**Comment by sotojuan** [comment]
Just got this merged. Let me know if it's what you were asking for

**Comment by Avaq** [comment]
I left some comments on the commit: https://github.com/sotojuan/fugot/commit/38200837485fd7032b4ba9b43a819f7b84d00db7

**Comment by sotojuan** [comment]
Thanks - not very experienced with peer deps. Got it.

**Comment by Avaq** [comment]
:+1: It looks good now.
